name: Deploy to GitHub Pages  # Tên workflow, sẽ hiển thị trong tab "Actions" của GitHub

on:  # Khi nào chạy workflow này
  push:
    branches: [main]  # Chỉ chạy khi push code lên nhánh main

permissions:
  contents: read        # Cho phép đọc nội dung repo
  pages: write          # Cho phép ghi nội dung lên GitHub Pages
  id-token: write       # Cấp token xác thực cho GitHub Pages

jobs:
  build:  # Job đầu tiên tên là 'build'
    runs-on: ubuntu-latest  # Chạy trên hệ điều hành Ubuntu

    steps:
      - name: Checkout code  # Bước 1: Lấy mã nguồn từ GitHub repo
        uses: actions/checkout@v4

      - name: Setup Pages  # Bước 2: Cấu hình môi trường GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload static site  # Bước 3: Upload toàn bộ file HTML/CSS/JS để chuẩn bị deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload toàn bộ nội dung thư mục gốc (nơi có index.html)

  deploy:  # Job thứ hai tên là 'deploy'
    needs: build  # Chạy sau khi job 'build' hoàn thành
    runs-on: ubuntu-latest

    environment:
      name: github-pages  # Tên môi trường
      url: ${{ steps.deployment.outputs.page_url }}  # Tự động l_


     
     